INSERT INTO CITIZENS (ID,CREATED_AT,UPDATED_AT,FIRSTNAME,SURNAME) VALUES (2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'MARIUSZ','PYSZCZUK');
INSERT INTO CITIZENS (ID,CREATED_AT,UPDATED_AT,FIRSTNAME,SURNAME) VALUES (3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'LESZEK','BUBICKI');
INSERT INTO EMAILADDRESSES (ID,CREATED_AT,UPDATED_AT,EMAIL_ADDRESS,CITIZENS_ID) VALUES (1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'bubicki@bubicki.pl',3);
INSERT INTO EMAILADDRESSES (ID,CREATED_AT,UPDATED_AT,EMAIL_ADDRESS,CITIZENS_ID) VALUES (2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'leszek@bubicki.pl',3);
